remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
github:
  is_project_page: false
title: "RENT A HACK3R"
description: "[ERROR: SYSTEM COMPROMISED] Elite hacking collective. Premium services for the discerning client. Systems secured and protocols deployed."
